global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
#  - job_name: 'pushgateway'
#    honor_labels: true
#    static_configs:
#      - targets: ['localhost:9091']
  - job_name: 'node'
    file_sd_configs:
      - files:
        - 'targets.json'
        refresh_interval: 1m
  - job_name: 'server1_db'
    static_configs:
      - targets: ['79.174.94.98:9104']
        labels:
          alias: 'db1'
  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
      - targets: ['79.174.94.98:4040']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://79.174.94.98
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
